### ISSUE TITLE
What would cause an erroneous reading?

### ISSUE THREAD

**Issue by stevevance** [danwahl/adanet-co2-monitor#19]
Today I saw an error message for the first time. 

“Invalid sample detected”. 
I checked the code: it looks like the error is thrown if the reading is zero. 

check out the photo 
![13EE3B6E-6F35-4D68-A82E-157153383544](https://user-images.githubusercontent.com/1330459/210290723-6d969f04-3535-4933-8576-75a073c984a2.jpeg)

**Comment by danwahl** [comment]
Looks like you already found this, but for reference, it comes from [here](https://github.com/danwahl/adanet-co2-monitor/blob/v0.2.0/adanet-co2-monitor.ino#L322-L326) in the code: the SCD4x (CO2 sensor) reading did not return an error, but the reported CO2 value was 0 ppm (which is an [invalid response](https://github.com/Sensirion/arduino-i2c-scd4x/blob/0.3.1/examples/exampleUsage/exampleUsage.ino#L113-L114)).

I've seen this happen a few times, typically when I was handling the Adanet device during a measurement. I _think_ it's related to [the way photoacoustic NDIR sensors work](https://sensirion.com/media/documents/9E7DA521/627C2C8D/CD_IN_SCDxx_Transmissive_and_photoacoustic_NDIR_sensing_D1.pdf), but can't remember where I read that.

Did it go back to normal operation on the next update?

**Comment by stevevance** [comment]
It went back to normal operation on the next update. 

I wonder if the shopping cart caused an issue: The cart's wheels or axle had flat spots and the car was making the Adanet bounce on that rack. 

Why is `0` an invalid response? Couldn't the device plausibly detect the absence of CO2? Or is it not sensitive enough to confidently measure that?

**Comment by danwahl** [comment]
Agreed, that's probably it re: the shopping cart. Good question re: why `0` is an invalid response. The [data sheet](https://web.archive.org/web/20221012210846/https://sensirion.com/media/documents/C4B87CE6/627C2DCD/CD_DS_SCD40_SCD41_Datasheet_D1.pdf) even says that `0` is within the valid range.

An uninformed guess: part of the sensor's measurement cycle is probably some sort of calibration of the microphone part of the photoacoustic assembly relative to the current ambient noise. If it got a particularly large reading due to a disturbance during this step, it might set its baseline noise level too high, and be unable to detect any CO2 signal on top of it, causing it to report `0`.

If that's correct, it would be able accurately detect the absence of CO2, at least in a relatively quiet environment...

**Comment by stevevance** [comment]
thanks for the discussion! I'm gonna close this since I'm satisfied with the answer and I don't think it's worth refactoring the error message/detection.
